name: $(Build.DefinitionName)_$(Build.SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: "Ubuntu-latest"

trigger:
  - main

parameters:
  - name: env
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - systemtest_manual
      - systemtest_auto
      - system_integration_test
      - uat
      - pre_prod
      - production
  - name: devops_library_branch
    displayName: DevOps Library Branch
    type: string
    default: main
  - name: run_github_security_scan
    displayName: Run GitHub Advanced Security Scan
    type: boolean
    default: true
  - name: browser
    displayName: Select a Browser
    type: string
    default: chromium
    values:
      - chromium
      - safari
      - firefox


variables:
  - name: vstsFeed
    value: "0e030eb0-cb72-4f42-b99a-26e6544271c3/0a3e0ad2-23b6-4e8b-ae12-cd6d01fe97e7"
  - name: solution
    value: "**/*.sln"
  - name: project
    value: "**/*.csproj"
  - name: buildConfiguration
    value: "Release"

resources:
  repositories:
    - repository: library
      type: git
      name: DevOps/rsp-azure-devops-library
      ref: ${{ parameters.devops_library_branch }}

stages:
  - template: jobs/build.yaml@library
    parameters:
      run_github_security_scan: ${{ parameters.run_github_security_scan }}
      browser: ${{ parameters.browser }}