// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rsp.IrasService.Infrastructure;

#nullable disable

namespace Rsp.IrasService.Infrastructure.Migrations
{
    [DbContext(typeof(IrasContext))]
    [Migration("20240526171726_AddStatusColumnWithData")]
    partial class AddStatusColumnWithData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rsp.IrasService.Domain.Entities.IrasApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationCategories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Location")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IrasApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationCategories = "[\"Application category 1\",\"Application category 2\"]",
                            Location = 0,
                            ProjectCategory = "Project category 1",
                            StartDate = new DateTime(2024, 5, 26, 18, 17, 26, 124, DateTimeKind.Local).AddTicks(181),
                            Status = "pending",
                            Title = "Example 1"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationCategories = "[\"Application category 1\",\"Application category 2\"]",
                            Location = 1,
                            ProjectCategory = "Project category 2",
                            StartDate = new DateTime(2024, 5, 26, 18, 17, 26, 124, DateTimeKind.Local).AddTicks(264),
                            Status = "approved",
                            Title = "Example 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
