// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rsp.IrasService.Infrastructure;

#nullable disable

namespace Rsp.IrasService.Infrastructure.Migrations
{
    [DbContext(typeof(IrasContext))]
    [Migration("20240520133443_InitialiseWithIrasApplicaionEntity")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rsp.IrasService.Domain.Entities.IrasApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationCategories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Location")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IrasApplications");
                });

            modelBuilder.Entity("Rsp.IrasService.Domain.Entities.ResearchApplication", b =>
            {
                b.Property<int>("ApplicationId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Status")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UpdatedBy")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.HasKey("ApplicationId");

                b.ToTable("ResearchApplications");
            });

            modelBuilder.Entity("Rsp.IrasService.Domain.Entities.Respondent", b =>
            {
                b.Property<int>("RespondentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RespondentId"));

                b.Property<DateTime?>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Version")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("RespondentId");

                b.ToTable("Respondents");
            });

            modelBuilder.Entity("Rsp.IrasService.Domain.Entities.RespondentAnswer", b =>
            {
                b.Property<int>("RespondentId")
                    .HasColumnType("int");

                b.Property<string>("QuestionId")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("ApplicationId")
                    .HasColumnType("int");

                b.Property<DateTime?>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<string>("OptionId")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Response")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Version")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("RespondentId", "QuestionId", "ApplicationId");

                b.ToTable("RespondentAnswers");
            });

            modelBuilder.Entity("Rsp.IrasService.Domain.Entities.RespondentAnswer", b =>
            {
                b.HasOne("Rsp.IrasService.Domain.Entities.Respondent", null)
                    .WithMany("RespondentAnswers")
                    .HasForeignKey("RespondentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
